// GENERADO POR scripts/gen-types.sh — NO EDITAR A MANO.
// Fuente: backend/mewsplit/api.py (esquema OpenAPI de FastAPI).
// Regenerar tras cualquier cambio en los modelos de la API.

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Sin token: el sidecar la usa para saber cuándo el backend está vivo.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Job */
        post: operations["create_job_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Job */
        get: operations["read_job_jobs__job_id__get"];
        put?: never;
        post?: never;
        /** Delete Job */
        delete: operations["delete_job_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/stems/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Stem */
        get: operations["read_stem_jobs__job_id__stems__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_create_job_jobs_post */
        Body_create_job_jobs_post: {
            /** File */
            file: string;
        };
        /** ChordOut */
        ChordOut: {
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Chord */
            chord: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Ok */
            ok: boolean;
            /** Version */
            version: string;
            /** Device */
            device: string;
            /** Models */
            models: {
                [key: string]: string;
            };
        };
        /**
         * JobOut
         * @description Espejo tipado de `core.Analysis` para que OpenAPI (y por tanto
         *     `shared/types.ts`) tenga un contrato explícito. La duplicación es
         *     deliberada: mantiene a `core` libre de dependencias de transporte.
         */
        JobOut: {
            /** Id */
            id: string;
            status: components["schemas"]["Status"];
            /** Filename */
            filename: string;
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /**
             * Chords Ready
             * @default false
             */
            chords_ready: boolean;
            /** Error */
            error?: string | null;
            /** Device */
            device?: string | null;
            /** Model */
            model?: string | null;
            /** Duration */
            duration?: number | null;
            /**
             * Stems
             * @default {}
             */
            stems: {
                [key: string]: string;
            };
            /** Instrumental */
            instrumental?: string | null;
            /**
             * Chords
             * @default []
             */
            chords: components["schemas"]["ChordOut"][];
            /**
             * Timings
             * @default {}
             */
            timings: {
                [key: string]: number;
            };
        };
        /**
         * Status
         * @enum {string}
         */
        Status: "queued" | "processing" | "done" | "error";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    create_job_jobs_post: {
        parameters: {
            query?: {
                model?: string;
                with_chords?: boolean;
                large_vocabulary?: boolean;
            };
            header?: {
                "x-mewsplit-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_job_jobs_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_job_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-mewsplit-token"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_job_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-mewsplit-token"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_stem_jobs__job_id__stems__name__get: {
        parameters: {
            query?: never;
            header?: {
                "x-mewsplit-token"?: string | null;
            };
            path: {
                job_id: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
